version: '3.8'

services:
  app:
    env_file:
       - env_stack.env
    image: simple-node-app
    ports:
      - "8000:8000"
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
      
    healthcheck:
      test: curl -sS http://localhost:8000/hostname || echo 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
